Greed
GMBoreas/trocalculator pull request #370
Opened 2020-07-30 08:08 UTC by Isilla666

Need to discuss about the second call KakutyouKansuu(); after calculation of battle and using document.getElementById("strID_1").textContent

2020-08-23 20:13 UTC, Hatfun commented on js/card.js
> +,[46,1,"Hunter Fly","Enables a 3% chance of gaining 15% of the damage inflicted on an enemy as HP with each attack",380,3,381,15,0]
I think it would be better if drain description is directly part of the generated descriptions in item.js
But it might not be easy since it's split into 2 separate n_tok variables...

2020-08-23 20:15 UTC, Hatfun commented on js/foot.js
> +				var mobCount = eval(document.calcForm.A_KakutyouSelNum.value);
Not important, but parseInt() might better than eval() if it's just to convert the entry to an int value.

2020-08-23 20:18 UTC, Hatfun commented on js/foot.js
> +		w = '<Font size="2">Number of monsters<input type="text" name="A_KakutyouSelNum" value="1" size=4 onChange="StAllCalc()" style="text-align : right;"><BR>';
minor UI adjustment to be better aligned:
`		w = '<div style="float:left;margin-right:10px;padding-top:4px">Number of monsters:</div><div style="float:left"><input type="text" name="A_KakutyouSelNum" value="1" size=4 onChange="StAllCalc()" style="text-align : right"></div><div style="clear:both"></div>';
`

2020-08-23 20:24 UTC, Hatfun commented on js/item.js
> +      CBIstr +="";
Yeah, not easy to incorporate the item description here...
I can think of a "way", but it's more like a hack. We can assume this function is called within a loop (first 380/382, then 381/383). So when 380/382 is called, we keep the value in a global variable, and when 381/383 is called, then we can use the stored variable to write the full description.

2020-08-23 21:18 UTC, Isilla666 commented on js/card.js
> +,[46,1,"Hunter Fly","Enables a 3% chance of gaining 15% of the damage inflicted on an enemy as HP with each attack",380,3,381,15,0]
Better not to do this because in the original these are two completely different functions.

2020-08-23 21:19 UTC, Isilla666 commented on js/item.js
> +      CBIstr +="";
Better not to do this because in the original these are two completely different functions.
(bonus2 bHPDrainRate / bonus bHPrecovRate)

2020-08-23 21:22 UTC, Isilla666 commented on js/foot.js
> +				var mobCount = eval(document.calcForm.A_KakutyouSelNum.value);
I tend to ensure that the code is everywhere similar and identical for each module.

2020-08-23 21:30 UTC, Isilla666 commented on js/foot.js
> +		w = '<Font size="2">Number of monsters<input type="text" name="A_KakutyouSelNum" value="1" size=4 onChange="StAllCalc()" style="text-align : right;"><BR>';
Сhanged

2020-11-24 14:58 UTC, victorgawk commented
> I have one question about the drain rate, that I actually don't know how it works in game, and how it should be reflected in calc...
> For the specific case of Bowling Bash, which is 2 separate hits in 1 skill. Does the drain work on just 1 out of the 2 hits? or for both? Does that matter for the drain rate calculation since it's "twice the chance" within 1 skill?

on rAthena the drain works for both hits, and the drain of each hit is tested individually.

2020-11-24 16:23 UTC, victorgawk requested changes

2020-11-24 16:23 UTC, victorgawk commented on js/foot.js
> +					wkk17+="<tr><td>Result: ~<b>"+Math.floor(mobCount*(n_tok[380]>100?100:n_tok[380])*n_tok[381]*avergeAtk/10000)+"</b>("+Math.floor(mobCount*n_tok[381]*avergeAtk/100)+" maximum) per hit</td>"+"<td>
You should `Math.floor` the individual hp or sp that can be drained per hit before multiplying it by the mob quantity and the drain chance. Also I think there is no need to `Math.floor` the result of multiplication with the drain chance and mob quantity, I would keep the decimal part instead.

Below is my suggestion:
```
wkk17+="<tr><td>Result: ~<b>"+mobCount*(n_tok[380]>100?100:n_tok[380])*Math.floor(n_tok[381]*avergeAtk/100)/100+"</b>("+mobCount*Math.floor(n_tok[381]*avergeAtk/100)+" maximum) per hit</td>"+"<td></td>"+"<td>Result: ~<b>"+mobCount*(n_tok[382]>100?100:n_tok[382])*Math.floor(n_tok[383]*avergeAtk/100)/100+"</b>("+mobCount*Math.floor(n_tok[383]*avergeAtk/100)+" maximum) per hit</td></tr>";
```

2020-11-24 16:23 UTC, victorgawk commented on js/foot.js
> +					}
For DPS part, instead of `Math.floor` the entire result, you could keep 2 digits of the decimal part. Below my suggestion (keep 2 digits of the decimal part):
```
var dps = parseInt(document.getElementById("AveSecondATK").textContent);
if(dps>=0){
	wkk17+="<tr><td>~<b>"+Math.round((mobCount*(n_tok[380]>100?100:n_tok[380])*n_tok[381]*dps/10000)*100)/100+"</b> per second</td>"+"<td></td>"+"<td>~<b>"+Math.round((mobCount*(n_tok[382]>100?100:n_tok[382])*n_tok[383]*dps/10000)*100)/100+"</b> per second</td></tr>";
}
```

2020-11-25 14:53 UTC, victorgawk commented on js/foot.js
> +					}
also, for a more precise "Drain HP/SP Per Second" calculation, instead of using the "dps" variable, you could calculate by yourself based on the aspd formula from function `BattleCalc998()` (`head.js` file). Below the result:
```
var drainHPperSec = Math.round(100 / (wCast + wDelay) * Math.floor(n_tok[381]*avergeAtk/100))/100;
var drainSPperSec = Math.round(100 / (wCast + wDelay) * Math.floor(n_tok[383]*avergeAtk/100))/100;
if(dps>=0){
	wkk17+="<tr><td>~<b>"+Math.round((mobCount*(n_tok[380]>100?100:n_tok[380])*drainHPperSec/100)*100)/100+"</b> per second</td>"+"<td></td>"+"<td>~<b>"+Math.round((mobCount*(n_tok[382]>100?100:n_tok[382])*drainSPperSec/100)*100)/100+"</b> per second</td></tr>";
}
```

2020-12-21 02:16 UTC, merged